### ISSUE TITLE
Ismp Parachain should identify parachains with 6s slots

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/hyperbridge#223]
We currently hard code the expected slot duration for parachains which is used to calculate it's current timestamp. For parachains with async backing (like hyperbridge), this slot duration will instead be 6s. We should add some metadata about parachains which tell the ismp parachain consensus client what slot number that the parachain currently uses. This should be configured when the parachain is added to the pallet.

**Comment by MrishoLukamba** [comment]
I do think, hyperbridge should only focus 6s slot time parachains. As the end of the day all parachains will upgrade

**Comment by seunlanlege** [comment]
closed in #253
