### ISSUE TITLE
Testnet Token request for Faucet

### ISSUE THREAD

**Issue by gagan7gb** [polytope-labs/hyperbridge#232]
Hello, I am one of the contributors to the Universal Substrate Faucet funded by the Polkadot Treasury(https://polkadot.polkassembly.io/referenda/541).
Please help us acquire the testnet tokens for Hyperbridge (Gargantua).

**Comment by seunlanlege** [comment]
Hyperbridge doesn't host any extrinsics that users can call directly. Instead users pay Hyperbridge through our fee token on a connected chain.

You can find the testnet addresses for the fee token and token faucet here: 
https://docs.hyperbridge.network/developers/evm/contract-addresses
