### ISSUE TITLE
[hyperclient] Logging

### ISSUE THREAD

**Issue by niklasp** [polytope-labs/hyperbridge#321]
Browsers don't support colors in logging.

<img width="696" alt="Bildschirmfoto 2024-10-08 um 12 59 00" src="https://github.com/user-attachments/assets/248d5b93-2786-4acd-a47f-9f0f2b1edc25">

Disable in js or add add a way to disable loggin in HyperClient?

**Comment by seunlanlege** [comment]
Will disable logging
