### ISSUE TITLE
Benchmark `ismp-parachain`

### ISSUE THREAD

**Issue by seunlanlege** [polytope-labs/hyperbridge#349]
Would be nice to have benchmarks for `ismp-parachain` since it doesn't have any dynamic logic like `pallet-ismp`

**Comment by sylvaincormier** [comment]
Hi I might as well do this one too? If you don't mind.

**Comment by seunlanlege** [comment]
> Hi I might as well do this one too? If you don't mind.
> 
> 

Please do!
